---
- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"

- name: Install Certbot OVH Plugin.
  package: "name={{ certbot_ovh_package }} state=present"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
